name: dartchat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  page_transition: ^1.1.6
  get_it: ^4.0.4
  flutter_keyboard_visibility: ^3.2.1
  provider: ^5.0.0
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.3
  cloud_firestore: ^1.0.4
  firebase_storage: ^8.0.3
  firebase_messaging: ^9.1.1
  image_picker: ^0.7.4
  # cached_network_image: ^2.2.0+1
  dartz: ^0.9.1
  equatable: ^2.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  data_connection_checker: ^0.3.4
  rxdart: ^0.26.0
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  permission: ^0.1.7
  cached_network_image: ^3.0.0
  percent_indicator: ^3.0.1
  image: ^3.0.2
  path_provider: ^2.0.1
  cached_video_player: ^1.0.3
  video_thumbnail: ^0.3.3

dev_dependencies:
  hive_generator: ^1.0.1
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/images/placeholders/
  fonts:
    - family: Arial Rounded
      fonts:
        - asset: assets/fonts/ARLRDBD.TTF
